title: Nikita Vasilyev
author: Nikita Vasilyev
name: n12v
domain: n12v.com
url: http://n12v.com

root: /
permalink: /:title/
source: source
destination: public
plugins: plugins

pygments: false

excerpt_separator: '<!-- more -->'

dev: true

# Used only for JS
asset_bundler:
  compress:
    js: java -jar ~/closure/latest.jar --js :infile --js_output_file :outfile
    #  --compilation_level ADVANCED_OPTIMIZATIONS
    css: false
  markup_templates:
      js: '<script src="{{url}}"></script>'
      css: '<link rel=stylesheet href="{{url}}">'
  base_path: /
  cdn:
  remove_bundled: true
  dev: true
  bundle_name: 'min'

# Used only for SCSS/Compass
asset_pipeline:
  bundle: false            # Default = true
  compress: false          # Default = true
  output_path: css     # Default = assets
  gzip: false
#  display_path: nil
