title: Nikita Vasilyev
author: Nikita Vasilyev
name: n12v
domain: n12v.com
url: http://n12v.com

root: /
permalink: /:title/
source: source
destination: public
plugins: plugins

# Jekyll v1
pygments: false
# Jelyll v3
# highlighter: null

excerpt_separator: '<!-- more -->'

dev: true

# Used only for JS
asset_bundler:
  compress:
    js: ./vendor/closure-compiler --js :infile --js_output_file :outfile
    #  --compilation_level ADVANCED_OPTIMIZATIONS
    css: false
  markup_templates:
      js: '<script src="{{url}}"></script>'
      css: '<link rel=stylesheet href="{{url}}">'
  base_path: /
  cdn:
  remove_bundled: true
  dev: true
  bundle_name: 'min'
